name = "harman-handloom"
main = ".open-next/worker.js"
compatibility_date = "2026-04-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "harman-db"
database_id = "f0f592b3-76f2-42ab-b476-258cd63d576e"
